# Generated by Django 3.0.2 on 2020-01-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('days_available', models.CharField(max_length=255)),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
            ],
            options={
                'permissions': [('manage', 'Can create/edit/delete a bookable and inputs.')],
            },
        ),
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment pending'), ('cancelled', 'Payment cancelled'), ('failed', 'Payment failed'), ('completed', 'Payment completed')], default='pending', max_length=15)),
                ('stripe_session_id', models.CharField(max_length=255)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_booked_services', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookableInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('ft_text', 'Text'), ('ft_text_multiline', 'Text multi-line'), ('ft_date', 'Date'), ('ft_time', 'Time'), ('ft_address', 'Address'), ('ft_checkbox', 'Checkbox')], default='ft_text', max_length=25)),
                ('field_required', models.BooleanField(default=False)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='booking.Bookable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
