# Generated by Django 3.0.2 on 2020-01-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedservice',
            options={'ordering': ['-created']},
        ),
    ]
