# Generated by Django 3.0.2 on 2020-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200130_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
