# Generated by Django 3.0.2 on 2020-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200130_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedservice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
