# Generated by Django 3.0.2 on 2020-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookedservice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookableinput',
            name='field_type',
            field=models.CharField(choices=[('ft_text', 'Text'), ('ft_text_multiline', 'Text multi-line'), ('ft_date', 'Date'), ('ft_time', 'Time')], default='ft_text', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookedservice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment pending'), ('completed', 'Payment completed')], default='pending', max_length=15),
        ),
    ]
