# Generated by Django 3.0.2 on 2020-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200130_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookableinput',
            name='field_type',
            field=models.CharField(choices=[('ft_text', 'Text'), ('ft_text_multiline', 'Text multi-line'), ('ft_date', 'Date'), ('ft_time', 'Time'), ('ft_checkbox', 'Checkbox')], default='ft_text', max_length=25),
        ),
    ]
